import type { GameDataCatalog } from './schemas.js';

export const GAME_DATA_VERSION = '2026.07.30.1' as const;
export const BALANCE_VERSION = '2026.07.30.1' as const;

/** Data only: formulas and numerical combat tuning remain deliberately TBD in Step 2. */
export const GAME_DATA: GameDataCatalog = {
  version: GAME_DATA_VERSION,
  balance: {
    version: BALANCE_VERSION,
    tuningStatus: 'TBD',
    awayMode: {
      calibrationSeconds: 300,
      minimumRewardSeconds: 600,
      maximumRewardSeconds: 28_800,
      efficiency: 0.8,
      formulaVersion: 'away-formula.1',
    },
    multiplayer: {
      minimumPlayers: 1,
      maximumPlayers: 4,
      healthPerAdditionalPlayer: 0.65,
      damagePerAdditionalPlayer: 0.15,
    },
    visual: { standardFrameSize: 64, largeFrameSize: 128 },
  },
  guardianCombat: {
    combatFormulaVersion: 'guardian-combat.1',
    tuningStatus: 'PROVISIONAL',
    level: 1,
    attributes: { strength: 10, dexterity: 5, intelligence: 3, vitality: 12 },
    weaponDamage: [10, 14],
    maxFury: 100,
    criticalBaseChance: 0.05,
    criticalPerDexterity: 0.005,
    criticalCap: 0.5,
    criticalMultiplier: 1.5,
    armorDenominatorBase: 100,
    armorDenominatorPerLevel: 50,
    armorReductionCap: 0.75,
    furyOnDamageTaken: 5,
    furyDecayDelayMs: 3000,
    furyDecayPerSecond: 5,
    battleThirst: { healFraction: 0.05, capFraction: 0.15, windowMs: 10_000 },
    abilities: [
      {
        id: 'ability.guardian.slash',
        input: 'primary',
        furyCost: 0,
        cooldownMs: 500,
        damageMultiplier: 1,
        rangePx: 78,
        arcDegrees: 100,
        maxTargets: 3,
        impactMs: 200,
        recoveryMs: 500,
        furyOnHit: 10,
      },
      {
        id: 'ability.guardian.power_strike',
        input: 'secondary',
        furyCost: 30,
        cooldownMs: 4000,
        damageMultiplier: 2.25,
        rangePx: 90,
        arcDegrees: 80,
        maxTargets: 3,
        impactMs: 400,
        recoveryMs: 800,
        knockbackPx: 128,
      },
      {
        id: 'ability.guardian.whirlwind',
        input: 'q',
        furyCost: 40,
        cooldownMs: 7000,
        damageMultiplier: 0.45,
        radiusPx: 96,
        durationMs: 1200,
        tickOffsetsMs: [0, 300, 600, 900],
        movementMultiplier: 0.65,
      },
      {
        id: 'ability.guardian.iron_skin',
        input: 'e',
        furyCost: 25,
        cooldownMs: 12000,
        damageMultiplier: 0,
        impactMs: 250,
        recoveryMs: 500,
        durationMs: 4000,
        damageTakenMultiplier: 0.55,
      },
      {
        id: 'ability.guardian.battle_thirst',
        input: 'passive',
        furyCost: 0,
        cooldownMs: 0,
        damageMultiplier: 0,
      },
    ],
  },
  guardian: {
    id: 'guardian',
    displayName: 'Guardián',
    role: 'melee_resilient',
    resource: 'fury',
    attributeKeys: ['strength', 'dexterity', 'intelligence', 'vitality'],
    attributeIds: ['strength', 'dexterity', 'intelligence', 'vitality'],
    abilityIds: [
      'ability.guardian.slash',
      'ability.guardian.power_strike',
      'ability.guardian.whirlwind',
      'ability.guardian.iron_skin',
      'ability.guardian.battle_thirst',
    ],
  },
  attributes: [
    {
      id: 'strength',
      displayName: 'Fuerza',
      semanticEffects: ['physical_damage', 'heavy_equipment_access', 'armor'],
      tuningStatus: 'TBD',
    },
    {
      id: 'dexterity',
      displayName: 'Destreza',
      semanticEffects: ['critical_chance', 'accuracy', 'attack_speed_minor'],
      tuningStatus: 'TBD',
    },
    {
      id: 'intelligence',
      displayName: 'Inteligencia',
      semanticEffects: ['elemental_resistance', 'effect_effectiveness'],
      tuningStatus: 'TBD',
    },
    {
      id: 'vitality',
      displayName: 'Vitalidad',
      semanticEffects: ['max_health', 'recovery', 'status_resistance'],
      tuningStatus: 'TBD',
    },
  ],
  abilities: [
    {
      id: 'ability.guardian.slash',
      kind: 'basic_attack',
      displayName: 'Tajo',
      description: 'Ataque frontal corto que genera Furia.',
      animationId: 'guardian.attack_basic.down',
      mechanics: ['short_frontal_targeting', 'nearby_multi_target', 'generates_fury'],
      tuningStatus: 'TBD',
    },
    {
      id: 'ability.guardian.power_strike',
      kind: 'active',
      displayName: 'Golpe poderoso',
      description: 'Ataque lento que empuja y consume Furia.',
      animationId: 'guardian.skill_power_strike.down',
      mechanics: ['slow_attack', 'high_damage', 'knockback', 'consumes_fury'],
      tuningStatus: 'TBD',
    },
    {
      id: 'ability.guardian.whirlwind',
      kind: 'active',
      displayName: 'Torbellino',
      description: 'Daño alrededor del personaje con movimiento reducido.',
      animationId: 'guardian.skill_whirlwind.down',
      mechanics: ['self_area_damage', 'consumes_fury', 'brief_duration', 'reduced_movement'],
      tuningStatus: 'TBD',
    },
    {
      id: 'ability.guardian.iron_skin',
      kind: 'active',
      displayName: 'Piel de hierro',
      description: 'Reduce daño recibido sin otorgar invulnerabilidad.',
      animationId: 'guardian.skill_iron_skin.down',
      mechanics: ['temporary_damage_reduction', 'not_invulnerable', 'high_cooldown'],
      tuningStatus: 'TBD',
    },
    {
      id: 'ability.guardian.battle_thirst',
      kind: 'passive',
      displayName: 'Sed de batalla',
      description: 'Recupera vida limitada después de derrotar enemigos.',
      animationId: 'guardian.idle.down',
      mechanics: ['heal_on_kill', 'healing_capped'],
      tuningStatus: 'TBD',
    },
  ],
  itemTypes: [
    { id: 'weapon_one_hand', compatibleSlots: ['main_hand'], tuningStatus: 'TBD' },
    { id: 'weapon_two_hand', compatibleSlots: ['main_hand'], tuningStatus: 'TBD' },
    { id: 'shield', compatibleSlots: ['off_hand'], tuningStatus: 'TBD' },
    { id: 'helmet', compatibleSlots: ['helmet'], tuningStatus: 'TBD' },
    { id: 'chest', compatibleSlots: ['chest'], tuningStatus: 'TBD' },
    { id: 'gloves', compatibleSlots: ['gloves'], tuningStatus: 'TBD' },
    { id: 'boots', compatibleSlots: ['boots'], tuningStatus: 'TBD' },
    { id: 'amulet', compatibleSlots: ['amulet'], tuningStatus: 'TBD' },
    { id: 'ring', compatibleSlots: ['ring_1', 'ring_2'], tuningStatus: 'TBD' },
    { id: 'material', compatibleSlots: [], tuningStatus: 'TBD' },
  ],
  rarities: [
    {
      id: 'common',
      description: 'Estadísticas base sin afijos o con modificación mínima.',
      tuningStatus: 'TBD',
    },
    { id: 'magic', description: 'Uno o dos afijos.', tuningStatus: 'TBD' },
    { id: 'rare', description: 'Más afijos y valores superiores.', tuningStatus: 'TBD' },
    {
      id: 'legendary',
      description: 'Afijo especial que altera una habilidad o comportamiento.',
      tuningStatus: 'TBD',
    },
  ],
  enemies: [
    {
      id: 'corrupted_minion',
      displayName: 'Esbirro corrupto',
      behaviors: ['melee'],
      aiStates: [
        'idle',
        'patrol',
        'detect',
        'chase',
        'attack',
        'use_ability',
        'retreat',
        'stunned',
        'dead',
      ],
      tuningStatus: 'TBD',
    },
    {
      id: 'possessed_archer',
      displayName: 'Arquero poseído',
      behaviors: ['ranged', 'keep_distance', 'reposition'],
      aiStates: [
        'idle',
        'patrol',
        'detect',
        'chase',
        'attack',
        'use_ability',
        'retreat',
        'stunned',
        'dead',
      ],
      tuningStatus: 'TBD',
    },
    {
      id: 'dark_shaman',
      displayName: 'Chamán oscuro',
      behaviors: ['ranged', 'heal_allies', 'buff_allies'],
      aiStates: [
        'idle',
        'patrol',
        'detect',
        'chase',
        'attack',
        'use_ability',
        'retreat',
        'stunned',
        'dead',
      ],
      tuningStatus: 'TBD',
    },
    {
      id: 'root_brute',
      displayName: 'Bruto de raíces',
      behaviors: ['melee', 'area_attack', 'stun'],
      aiStates: [
        'idle',
        'patrol',
        'detect',
        'chase',
        'attack',
        'use_ability',
        'retreat',
        'stunned',
        'dead',
      ],
      tuningStatus: 'TBD',
    },
    {
      id: 'unstable_beast',
      displayName: 'Bestia inestable',
      behaviors: ['fast_pursuit', 'telegraphed_explosion'],
      aiStates: [
        'idle',
        'patrol',
        'detect',
        'chase',
        'attack',
        'use_ability',
        'retreat',
        'stunned',
        'dead',
      ],
      tuningStatus: 'TBD',
    },
  ],
  zone: {
    id: 'corrupted_forest',
    displayName: 'Bosque Corrupto',
    awayModeEligible: true,
    enemyIds: [
      'corrupted_minion',
      'possessed_archer',
      'dark_shaman',
      'root_brute',
      'unstable_beast',
    ],
    mapId: 'map.corrupted_forest',
    tuningStatus: 'TBD',
  },
  mission: {
    id: 'mission.corrupted_forest.breach',
    zoneId: 'corrupted_forest',
    objectives: [
      { type: 'destroy_altars', count: 3 },
      { type: 'defeat_boss', enemyId: 'corrupted_guardian' },
    ],
    tuningStatus: 'TBD',
  },
  spriteSheets: [
    {
      id: 'spritesheet.guardian.body.placeholder',
      frameWidth: 64,
      frameHeight: 64,
      frameCount: 4,
      origin: { x: 0.5, y: 1 },
      offset: { x: 0, y: 0 },
      directions: ['up', 'down', 'left', 'right'],
      mirrorLeftFromRight: true,
    },
  ],
  animations: [
    {
      id: 'guardian.idle.down',
      atlasId: 'spritesheet.guardian.body.placeholder',
      state: 'idle',
      direction: 'down',
      startFrame: 0,
      endFrame: 3,
      frameRate: 1,
      repeat: -1,
      lockMovement: false,
      interruptible: true,
      eventFrames: [],
    },
    {
      id: 'guardian.attack_basic.down',
      atlasId: 'spritesheet.guardian.body.placeholder',
      state: 'attacking',
      direction: 'down',
      startFrame: 0,
      endFrame: 3,
      frameRate: 1,
      repeat: 0,
      lockMovement: true,
      interruptible: false,
      hitFrame: 2,
      eventFrames: [{ frame: 2, event: 'combat.hit_window' }],
    },
    {
      id: 'guardian.skill_power_strike.down',
      atlasId: 'spritesheet.guardian.body.placeholder',
      state: 'casting',
      direction: 'down',
      startFrame: 0,
      endFrame: 3,
      frameRate: 1,
      repeat: 0,
      lockMovement: true,
      interruptible: false,
      hitFrame: 2,
      eventFrames: [{ frame: 2, event: 'combat.hit_window' }],
    },
    {
      id: 'guardian.skill_whirlwind.down',
      atlasId: 'spritesheet.guardian.body.placeholder',
      state: 'channeling',
      direction: 'down',
      startFrame: 0,
      endFrame: 3,
      frameRate: 1,
      repeat: 0,
      lockMovement: false,
      interruptible: true,
      eventFrames: [],
    },
    {
      id: 'guardian.skill_iron_skin.down',
      atlasId: 'spritesheet.guardian.body.placeholder',
      state: 'casting',
      direction: 'down',
      startFrame: 0,
      endFrame: 3,
      frameRate: 1,
      repeat: 0,
      lockMovement: false,
      interruptible: true,
      eventFrames: [],
    },
  ],
  assets: [
    {
      id: 'spritesheet.guardian.body.placeholder',
      type: 'spritesheet',
      path: '/assets/characters/guardian_body_placeholder.png',
      version: GAME_DATA_VERSION,
      preload: true,
      source: 'Proyecto La Brecha Oscura',
      author: 'Pendiente de producción',
      license: 'Placeholder interno',
      addedOn: '2026-07-29',
      approximateBytes: 0,
      animationIds: [
        'guardian.idle.down',
        'guardian.attack_basic.down',
        'guardian.skill_power_strike.down',
        'guardian.skill_whirlwind.down',
        'guardian.skill_iron_skin.down',
      ],
      spriteSheet: {
        id: 'spritesheet.guardian.body.placeholder',
        frameWidth: 64,
        frameHeight: 64,
        frameCount: 4,
        origin: { x: 0.5, y: 1 },
        offset: { x: 0, y: 0 },
        directions: ['up', 'down', 'left', 'right'],
        mirrorLeftFromRight: true,
      },
    },
  ],
  maps: [
    {
      id: 'map.corrupted_forest',
      format: 'tiled',
      version: GAME_DATA_VERSION,
      requiredLayers: [
        'ground',
        'decoration_lower',
        'collisions',
        'interactive_objects',
        'obstacles',
        'decoration_upper',
        'spawn_zones',
        'camera_zones',
        'altars',
        'doors',
        'portal',
        'boss_arena',
        'checkpoints',
        'ambient_sound',
        'minimap',
      ],
      objects: [
        {
          entityType: 'altar',
          definitionId: 'objective.corrupted_altar',
          objectiveId: 'objective.destroy_altars',
          serverRelevant: true,
        },
        {
          entityType: 'door',
          definitionId: 'door.corrupted_forest.boss',
          interactionId: 'interaction.open_boss_door',
          serverRelevant: true,
        },
        {
          entityType: 'boss_arena',
          definitionId: 'arena.corrupted_guardian',
          serverRelevant: true,
        },
      ],
    },
  ],
  hazards: [
    {
      id: 'hazard.corrupted_pulse',
      displayName: 'Pulso corrupto',
      periodMs: 4000,
      telegraphMs: 900,
      radiusPx: 90,
      damage: 18,
      lethal: false,
    },
  ],
};
