import type {
  AffixDefinition,
  EquipmentSlot,
  ItemDefinition,
  ItemStatRange,
  ItemType,
} from '@brecha/shared';

import type { GameDataCatalog } from './schemas.js';

export const GAME_DATA_VERSION = '2026.08.04.4' as const;
export const BALANCE_VERSION = '2026.08.04.4' as const;

const CHARACTER_PROGRESSION: GameDataCatalog['progression'] = {
  formulaVersion: 'character-progression.1',
  minimumLevel: 1,
  maximumLevel: 10,
  // Cumulative XP thresholds. Level 1 starts at zero; the last threshold is the level 10 cap.
  xpToReachLevel: [0, 100, 250, 450, 700, 1_000, 1_350, 1_750, 2_200, 2_700],
  attributePointsPerLevel: 3,
  resetCostPerLevel: 100,
};

/**
 * Builds the 20 levels of the endless Corrupted Forest with a PROVISIONAL monotonic scaling
 * (Paso 9): each level is strictly harder than the one before — enemy HP grows 25% per level,
 * enemy damage 10%, wave size by one, and the XP needed to advance grows so higher levels take
 * longer. Validation enforces monotonicity, so editing these constants can never accidentally
 * make a later level easier. The last level's `xpToAdvance` is unused (the player caps there).
 */
function buildEndlessForestLevels() {
  return Array.from({ length: 20 }, (_, index) => {
    const level = index + 1;
    const step = level - 1;
    return {
      level,
      enemyHealthMultiplier: 1 + step * 0.25,
      enemyDamageMultiplier: 1 + step * 0.1,
      waveSize: 3 + step,
      xpToAdvance: Math.round(100 * level * (1 + step * 0.15)),
    };
  });
}

function itemDefinition(
  id: string,
  displayName: string,
  type: ItemType,
  slot: EquipmentSlot,
  itemPowerRange: readonly [number, number],
  baseStats: readonly ItemStatRange[],
): ItemDefinition {
  return {
    id,
    displayName,
    type,
    slot,
    itemPowerRange: [itemPowerRange[0], itemPowerRange[1]],
    baseStats: baseStats.map((stat) => ({ ...stat })),
    tuningStatus: 'PROVISIONAL',
  };
}

const ITEM_DEFINITIONS: ItemDefinition[] = [
  itemDefinition(
    'item.weapon.iron_sword',
    'Espada de hierro',
    'weapon_one_hand',
    'main_hand',
    [8, 14],
    [
      { stat: 'physical_damage', min: 8, max: 12 },
      { stat: 'strength', min: 1, max: 3 },
    ],
  ),
  itemDefinition(
    'item.weapon.ash_saber',
    'Sable de ceniza',
    'weapon_one_hand',
    'main_hand',
    [12, 20],
    [
      { stat: 'physical_damage', min: 12, max: 18 },
      { stat: 'critical_chance', min: 1, max: 3 },
    ],
  ),
  itemDefinition(
    'item.weapon.moss_blade',
    'Hoja musgosa',
    'weapon_one_hand',
    'main_hand',
    [16, 25],
    [
      { stat: 'physical_damage', min: 16, max: 22 },
      { stat: 'vitality', min: 2, max: 5 },
    ],
  ),
  itemDefinition(
    'item.weapon.breach_falchion',
    'Falchión de la Brecha',
    'weapon_one_hand',
    'main_hand',
    [22, 34],
    [
      { stat: 'physical_damage', min: 22, max: 30 },
      { stat: 'strength', min: 4, max: 8 },
    ],
  ),
  itemDefinition(
    'item.weapon.dusk_axe',
    'Hacha del ocaso',
    'weapon_two_hand',
    'main_hand',
    [18, 30],
    [
      { stat: 'physical_damage', min: 20, max: 32 },
      { stat: 'strength', min: 4, max: 7 },
    ],
  ),
  itemDefinition(
    'item.weapon.root_hammer',
    'Martillo de raíces',
    'weapon_two_hand',
    'main_hand',
    [26, 40],
    [
      { stat: 'physical_damage', min: 28, max: 42 },
      { stat: 'vitality', min: 5, max: 9 },
    ],
  ),
  itemDefinition(
    'item.weapon.corrupted_greatsword',
    'Mandoble corrupto',
    'weapon_two_hand',
    'main_hand',
    [34, 52],
    [
      { stat: 'physical_damage', min: 36, max: 56 },
      { stat: 'strength', min: 7, max: 12 },
    ],
  ),
  itemDefinition(
    'item.weapon.guardian_halberd',
    'Alabarda del Guardián',
    'weapon_two_hand',
    'main_hand',
    [44, 68],
    [
      { stat: 'physical_damage', min: 48, max: 72 },
      { stat: 'armor', min: 6, max: 12 },
    ],
  ),
  itemDefinition(
    'item.weapon.briar_spear',
    'Lanza de zarzas',
    'weapon_two_hand',
    'main_hand',
    [50, 76],
    [
      { stat: 'physical_damage', min: 54, max: 80 },
      { stat: 'critical_chance', min: 3, max: 6 },
    ],
  ),
  itemDefinition(
    'item.weapon.corrupted_guardian',
    'Filo del Guardián Corrupto',
    'weapon_two_hand',
    'main_hand',
    [90, 120],
    [
      { stat: 'physical_damage', min: 100, max: 135 },
      { stat: 'strength', min: 14, max: 22 },
    ],
  ),
  itemDefinition(
    'item.armor.iron_helm',
    'Yelmo de hierro',
    'helmet',
    'helmet',
    [8, 14],
    [
      { stat: 'armor', min: 8, max: 14 },
      { stat: 'vitality', min: 1, max: 3 },
    ],
  ),
  itemDefinition(
    'item.armor.moss_crown',
    'Corona de musgo',
    'helmet',
    'helmet',
    [16, 24],
    [
      { stat: 'armor', min: 16, max: 24 },
      { stat: 'max_health', min: 8, max: 16 },
    ],
  ),
  itemDefinition(
    'item.armor.corrupted_helm',
    'Yelmo de corrupción',
    'helmet',
    'helmet',
    [30, 44],
    [
      { stat: 'armor', min: 30, max: 46 },
      { stat: 'strength', min: 4, max: 8 },
    ],
  ),
  itemDefinition(
    'item.armor.leather_cuirass',
    'Peto de cuero',
    'chest',
    'chest',
    [10, 18],
    [
      { stat: 'armor', min: 12, max: 20 },
      { stat: 'vitality', min: 2, max: 4 },
    ],
  ),
  itemDefinition(
    'item.armor.forest_cuirass',
    'Peto del bosque',
    'chest',
    'chest',
    [22, 34],
    [
      { stat: 'armor', min: 24, max: 38 },
      { stat: 'vitality', min: 5, max: 9 },
    ],
  ),
  itemDefinition(
    'item.armor.root_plate',
    'Placas de raíz',
    'chest',
    'chest',
    [38, 56],
    [
      { stat: 'armor', min: 42, max: 62 },
      { stat: 'max_health', min: 16, max: 28 },
    ],
  ),
  itemDefinition(
    'item.armor.iron_gloves',
    'Guanteletes de hierro',
    'gloves',
    'gloves',
    [7, 13],
    [
      { stat: 'armor', min: 6, max: 11 },
      { stat: 'strength', min: 1, max: 3 },
    ],
  ),
  itemDefinition(
    'item.armor.briar_grips',
    'Garras de zarza',
    'gloves',
    'gloves',
    [18, 28],
    [
      { stat: 'armor', min: 14, max: 24 },
      { stat: 'attack_speed_minor', min: 2, max: 5 },
    ],
  ),
  itemDefinition(
    'item.armor.traveler_boots',
    'Botas del viajero',
    'boots',
    'boots',
    [8, 15],
    [
      { stat: 'armor', min: 7, max: 12 },
      { stat: 'dexterity', min: 1, max: 3 },
    ],
  ),
  itemDefinition(
    'item.armor.corrupted_greaves',
    'Grebas corruptas',
    'boots',
    'boots',
    [22, 36],
    [
      { stat: 'armor', min: 20, max: 34 },
      { stat: 'max_health', min: 10, max: 18 },
    ],
  ),
  itemDefinition(
    'item.accessory.forest_amulet',
    'Amuleto del bosque',
    'amulet',
    'amulet',
    [14, 24],
    [
      { stat: 'vitality', min: 3, max: 7 },
      { stat: 'max_health', min: 10, max: 20 },
    ],
  ),
  itemDefinition(
    'item.accessory.breach_amulet',
    'Amuleto de la Brecha',
    'amulet',
    'amulet',
    [28, 44],
    [
      { stat: 'critical_chance', min: 2, max: 5 },
      { stat: 'physical_damage', min: 8, max: 16 },
    ],
  ),
  itemDefinition(
    'item.accessory.ash_ring',
    'Anillo de ceniza',
    'ring',
    'ring_1',
    [10, 18],
    [
      { stat: 'strength', min: 2, max: 5 },
      { stat: 'physical_damage', min: 4, max: 8 },
    ],
  ),
  itemDefinition(
    'item.accessory.moss_ring',
    'Anillo musgoso',
    'ring',
    'ring_1',
    [15, 25],
    [
      { stat: 'vitality', min: 3, max: 6 },
      { stat: 'armor', min: 5, max: 9 },
    ],
  ),
  itemDefinition(
    'item.accessory.corruption_ring',
    'Anillo de corrupción',
    'ring',
    'ring_1',
    [26, 42],
    [
      { stat: 'intelligence', min: 5, max: 10 },
      { stat: 'critical_chance', min: 2, max: 5 },
    ],
  ),
];

const AFFIXES: AffixDefinition[] = [
  {
    id: 'affix.power',
    displayName: 'Fuerza',
    family: 'offense',
    stat: 'strength',
    min: 2,
    max: 8,
    tuningStatus: 'PROVISIONAL',
  },
  {
    id: 'affix.precision',
    displayName: 'Precisión',
    family: 'offense',
    stat: 'critical_chance',
    min: 1,
    max: 4,
    tuningStatus: 'PROVISIONAL',
  },
  {
    id: 'affix.edge',
    displayName: 'Filo',
    family: 'offense',
    stat: 'physical_damage',
    min: 4,
    max: 14,
    tuningStatus: 'PROVISIONAL',
  },
  {
    id: 'affix.guard',
    displayName: 'Guardia',
    family: 'defense',
    stat: 'armor',
    min: 5,
    max: 18,
    tuningStatus: 'PROVISIONAL',
  },
  {
    id: 'affix.vigor',
    displayName: 'Vigor',
    family: 'defense',
    stat: 'vitality',
    min: 2,
    max: 9,
    tuningStatus: 'PROVISIONAL',
  },
  {
    id: 'affix.fortitude',
    displayName: 'Fortaleza',
    family: 'defense',
    stat: 'max_health',
    min: 10,
    max: 30,
    tuningStatus: 'PROVISIONAL',
  },
  {
    id: 'affix.haste',
    displayName: 'Celeridad',
    family: 'utility',
    stat: 'attack_speed_minor',
    min: 1,
    max: 4,
    tuningStatus: 'PROVISIONAL',
  },
  {
    id: 'affix.agility',
    displayName: 'Agilidad',
    family: 'utility',
    stat: 'dexterity',
    min: 2,
    max: 8,
    tuningStatus: 'PROVISIONAL',
  },
  {
    id: 'affix.focus',
    displayName: 'Enfoque',
    family: 'utility',
    stat: 'intelligence',
    min: 2,
    max: 8,
    tuningStatus: 'PROVISIONAL',
  },
  {
    id: 'affix.void',
    displayName: 'Vacío',
    family: 'corruption',
    stat: 'physical_damage',
    min: 8,
    max: 20,
    tuningStatus: 'PROVISIONAL',
  },
  {
    id: 'affix.dark_skin',
    displayName: 'Piel oscura',
    family: 'corruption',
    stat: 'armor',
    min: 8,
    max: 24,
    tuningStatus: 'PROVISIONAL',
  },
  {
    id: 'affix.breach',
    displayName: 'Brecha',
    family: 'corruption',
    stat: 'max_health',
    min: 15,
    max: 40,
    tuningStatus: 'PROVISIONAL',
  },
];

const ENEMY_LOOT_ENTRIES = ITEM_DEFINITIONS.map((definition) => ({
  definitionId: definition.id,
  weight: definition.id === 'item.weapon.corrupted_guardian' ? 1 : 10,
  dropChance: definition.id === 'item.weapon.corrupted_guardian' ? 0.01 : 0.35,
  minimumLevel: 1,
  maximumLevel: 20,
}));

/** Data only: formulas and numerical combat tuning remain deliberately TBD in Step 2. */
export const GAME_DATA: GameDataCatalog = {
  version: GAME_DATA_VERSION,
  balance: {
    version: BALANCE_VERSION,
    tuningStatus: 'TBD',
    awayMode: {
      calibrationSeconds: 300,
      minimumRewardSeconds: 600,
      maximumRewardSeconds: 28_800,
      efficiency: 0.8,
      formulaVersion: 'away-formula.1',
    },
    multiplayer: {
      minimumPlayers: 1,
      maximumPlayers: 4,
      healthPerAdditionalPlayer: 0.65,
      damagePerAdditionalPlayer: 0.15,
    },
    difficulty: {
      normal: { enemyHealthMultiplier: 1, enemyDamageMultiplier: 1 },
      veteran: { enemyHealthMultiplier: 1.25, enemyDamageMultiplier: 1.15 },
    },
    visual: { standardFrameSize: 64, largeFrameSize: 128 },
  },
  progression: CHARACTER_PROGRESSION,
  guardianCombat: {
    combatFormulaVersion: 'guardian-combat.1',
    tuningStatus: 'PROVISIONAL',
    level: 1,
    attributes: { strength: 10, dexterity: 5, intelligence: 3, vitality: 12 },
    weaponDamage: [10, 14],
    maxFury: 100,
    criticalBaseChance: 0.05,
    criticalPerDexterity: 0.005,
    criticalCap: 0.5,
    criticalMultiplier: 1.5,
    armorDenominatorBase: 100,
    armorDenominatorPerLevel: 50,
    armorReductionCap: 0.75,
    furyOnDamageTaken: 5,
    furyDecayDelayMs: 3000,
    furyDecayPerSecond: 5,
    battleThirst: { healFraction: 0.05, capFraction: 0.15, windowMs: 10_000 },
    abilities: [
      {
        id: 'ability.guardian.slash',
        input: 'primary',
        furyCost: 0,
        cooldownMs: 500,
        damageMultiplier: 1,
        rangePx: 78,
        arcDegrees: 100,
        maxTargets: 3,
        impactMs: 200,
        recoveryMs: 500,
        furyOnHit: 10,
      },
      {
        id: 'ability.guardian.power_strike',
        input: 'secondary',
        furyCost: 30,
        cooldownMs: 4000,
        damageMultiplier: 2.25,
        rangePx: 90,
        arcDegrees: 80,
        maxTargets: 3,
        impactMs: 400,
        recoveryMs: 800,
      },
      {
        id: 'ability.guardian.whirlwind',
        input: 'q',
        furyCost: 40,
        cooldownMs: 7000,
        damageMultiplier: 0.45,
        radiusPx: 96,
        durationMs: 1200,
        tickOffsetsMs: [0, 300, 600, 900],
        movementMultiplier: 0.65,
      },
      {
        id: 'ability.guardian.iron_skin',
        input: 'e',
        furyCost: 25,
        cooldownMs: 12000,
        damageMultiplier: 0,
        impactMs: 250,
        recoveryMs: 500,
        durationMs: 4000,
        damageTakenMultiplier: 0.55,
      },
      {
        id: 'ability.guardian.battle_thirst',
        input: 'passive',
        furyCost: 0,
        cooldownMs: 0,
        damageMultiplier: 0,
      },
    ],
  },
  guardian: {
    id: 'guardian',
    displayName: 'Guardián',
    role: 'melee_resilient',
    resource: 'fury',
    attributeKeys: ['strength', 'dexterity', 'intelligence', 'vitality'],
    attributeIds: ['strength', 'dexterity', 'intelligence', 'vitality'],
    abilityIds: [
      'ability.guardian.slash',
      'ability.guardian.power_strike',
      'ability.guardian.whirlwind',
      'ability.guardian.iron_skin',
      'ability.guardian.battle_thirst',
    ],
  },
  attributes: [
    {
      id: 'strength',
      displayName: 'Fuerza',
      semanticEffects: ['physical_damage', 'heavy_equipment_access', 'armor'],
      tuningStatus: 'TBD',
    },
    {
      id: 'dexterity',
      displayName: 'Destreza',
      semanticEffects: ['critical_chance', 'accuracy', 'attack_speed_minor'],
      tuningStatus: 'TBD',
    },
    {
      id: 'intelligence',
      displayName: 'Inteligencia',
      semanticEffects: ['elemental_resistance', 'effect_effectiveness'],
      tuningStatus: 'TBD',
    },
    {
      id: 'vitality',
      displayName: 'Vitalidad',
      semanticEffects: ['max_health', 'recovery', 'status_resistance'],
      tuningStatus: 'TBD',
    },
  ],
  abilities: [
    {
      id: 'ability.guardian.slash',
      kind: 'basic_attack',
      displayName: 'Tajo',
      description: 'Ataque frontal corto que genera Furia.',
      animationId: 'guardian.attack_basic.down',
      mechanics: ['short_frontal_targeting', 'nearby_multi_target', 'generates_fury'],
      unlockLevel: 1,
      tuningStatus: 'TBD',
    },
    {
      id: 'ability.guardian.power_strike',
      kind: 'active',
      displayName: 'Golpe poderoso',
      description: 'Ataque lento de alto daño que consume Furia.',
      animationId: 'guardian.skill_power_strike.down',
      mechanics: ['slow_attack', 'high_damage', 'consumes_fury'],
      unlockLevel: 2,
      tuningStatus: 'TBD',
    },
    {
      id: 'ability.guardian.whirlwind',
      kind: 'active',
      displayName: 'Torbellino',
      description: 'Daño alrededor del personaje con movimiento reducido.',
      animationId: 'guardian.skill_whirlwind.down',
      mechanics: ['self_area_damage', 'consumes_fury', 'brief_duration', 'reduced_movement'],
      unlockLevel: 4,
      tuningStatus: 'TBD',
    },
    {
      id: 'ability.guardian.iron_skin',
      kind: 'active',
      displayName: 'Piel de hierro',
      description: 'Reduce daño recibido sin otorgar invulnerabilidad.',
      animationId: 'guardian.skill_iron_skin.down',
      mechanics: ['temporary_damage_reduction', 'not_invulnerable', 'high_cooldown'],
      unlockLevel: 6,
      tuningStatus: 'TBD',
    },
    {
      id: 'ability.guardian.battle_thirst',
      kind: 'passive',
      displayName: 'Sed de batalla',
      description: 'Recupera vida limitada después de derrotar enemigos.',
      animationId: 'guardian.idle.down',
      mechanics: ['heal_on_kill', 'healing_capped'],
      unlockLevel: 8,
      tuningStatus: 'TBD',
    },
  ],
  itemTypes: [
    { id: 'weapon_one_hand', compatibleSlots: ['main_hand'], tuningStatus: 'TBD' },
    { id: 'weapon_two_hand', compatibleSlots: ['main_hand'], tuningStatus: 'TBD' },
    { id: 'shield', compatibleSlots: ['off_hand'], tuningStatus: 'TBD' },
    { id: 'helmet', compatibleSlots: ['helmet'], tuningStatus: 'TBD' },
    { id: 'chest', compatibleSlots: ['chest'], tuningStatus: 'TBD' },
    { id: 'gloves', compatibleSlots: ['gloves'], tuningStatus: 'TBD' },
    { id: 'boots', compatibleSlots: ['boots'], tuningStatus: 'TBD' },
    { id: 'amulet', compatibleSlots: ['amulet'], tuningStatus: 'TBD' },
    { id: 'ring', compatibleSlots: ['ring_1', 'ring_2'], tuningStatus: 'TBD' },
    { id: 'material', compatibleSlots: [], tuningStatus: 'TBD' },
  ],
  rarities: [
    {
      id: 'common',
      description: 'Estadísticas base sin afijos o con modificación mínima.',
      tuningStatus: 'TBD',
    },
    { id: 'magic', description: 'Uno o dos afijos.', tuningStatus: 'TBD' },
    { id: 'rare', description: 'Más afijos y valores superiores.', tuningStatus: 'TBD' },
    {
      id: 'legendary',
      description: 'Afijo especial que altera una habilidad o comportamiento.',
      tuningStatus: 'TBD',
    },
  ],
  itemDefinitions: ITEM_DEFINITIONS,
  affixes: AFFIXES,
  lootTables: [
    {
      id: 'loot.corrupted_forest.enemy',
      source: 'enemy_defeat',
      tuningStatus: 'PROVISIONAL',
      entries: ENEMY_LOOT_ENTRIES,
    },
  ],
  itemGeneration: {
    generatorVersion: 'items.mvp.1',
    rarityWeights: [
      { rarity: 'common', weight: 80 },
      { rarity: 'magic', weight: 15 },
      { rarity: 'rare', weight: 4 },
      { rarity: 'legendary', weight: 1 },
    ],
    affixCountByRarity: { common: 0, magic: 1, rare: 2, legendary: 1 },
  },
  enemies: [
    {
      id: 'corrupted_minion',
      displayName: 'Esbirro corrupto',
      behaviors: ['melee'],
      aiStates: [
        'idle',
        'patrol',
        'detect',
        'chase',
        'attack',
        'use_ability',
        'retreat',
        'stunned',
        'dead',
      ],
      tuningStatus: 'TBD',
    },
    {
      id: 'possessed_archer',
      displayName: 'Arquero poseído',
      behaviors: ['ranged', 'reposition'],
      aiStates: [
        'idle',
        'patrol',
        'detect',
        'chase',
        'attack',
        'use_ability',
        'retreat',
        'stunned',
        'dead',
      ],
      tuningStatus: 'TBD',
    },
    {
      id: 'dark_shaman',
      displayName: 'Chamán oscuro',
      behaviors: ['ranged', 'heal_allies', 'buff_allies'],
      aiStates: [
        'idle',
        'patrol',
        'detect',
        'chase',
        'attack',
        'use_ability',
        'retreat',
        'stunned',
        'dead',
      ],
      tuningStatus: 'TBD',
    },
    {
      id: 'root_brute',
      displayName: 'Bruto de raíces',
      behaviors: ['melee', 'area_attack', 'stun'],
      aiStates: [
        'idle',
        'patrol',
        'detect',
        'chase',
        'attack',
        'use_ability',
        'retreat',
        'stunned',
        'dead',
      ],
      tuningStatus: 'TBD',
    },
    {
      id: 'unstable_beast',
      displayName: 'Bestia inestable',
      behaviors: ['fast_pursuit', 'telegraphed_explosion'],
      aiStates: [
        'idle',
        'patrol',
        'detect',
        'chase',
        'attack',
        'use_ability',
        'retreat',
        'stunned',
        'dead',
      ],
      tuningStatus: 'TBD',
    },
  ],
  enemyTuning: [
    {
      enemyId: 'corrupted_minion',
      tuningStatus: 'PROVISIONAL',
      maxHealth: 40,
      armor: 5,
      moveSpeedPxPerSec: 90,
      separationRadiusPx: 28,
      detectRadiusPx: 220,
      loseTargetRadiusPx: 320,
      leashRadiusPx: 420,
      attack: {
        weaponDamage: [6, 8],
        power: 2,
        level: 1,
        criticalChance: 0.02,
        criticalMultiplier: 1.5,
        windupMs: 400,
        impactMs: 500,
        recoveryMs: 400,
        rangePx: 60,
        arcDegrees: 90,
        damageMultiplier: 0.8,
        cooldownMs: 1200,
      },
      telegraphMs: 300,
      xpReward: 10,
      goldReward: 5,
      materialsReward: 1,
      animationIds: [
        'enemy.corrupted_minion.idle.down',
        'enemy.corrupted_minion.moving.down',
        'enemy.corrupted_minion.attacking.down',
      ],
      frameSize: 64,
    },
    {
      enemyId: 'possessed_archer',
      tuningStatus: 'PROVISIONAL',
      maxHealth: 30,
      armor: 2,
      moveSpeedPxPerSec: 80,
      separationRadiusPx: 28,
      detectRadiusPx: 280,
      loseTargetRadiusPx: 400,
      leashRadiusPx: 500,
      attack: {
        weaponDamage: [5, 7],
        power: 2,
        level: 1,
        criticalChance: 0.04,
        criticalMultiplier: 1.5,
        windupMs: 600,
        impactMs: 700,
        recoveryMs: 500,
        rangePx: 260,
        arcDegrees: 40,
        damageMultiplier: 0.9,
        cooldownMs: 1800,
      },
      telegraphMs: 500,
      xpReward: 14,
      goldReward: 7,
      materialsReward: 1,
      animationIds: [
        'enemy.possessed_archer.idle.down',
        'enemy.possessed_archer.moving.down',
        'enemy.possessed_archer.attacking.down',
      ],
      frameSize: 64,
    },
    {
      enemyId: 'dark_shaman',
      tuningStatus: 'PROVISIONAL',
      maxHealth: 35,
      armor: 3,
      moveSpeedPxPerSec: 70,
      separationRadiusPx: 30,
      detectRadiusPx: 260,
      loseTargetRadiusPx: 380,
      leashRadiusPx: 480,
      attack: {
        weaponDamage: [4, 6],
        power: 3,
        level: 1,
        criticalChance: 0.03,
        criticalMultiplier: 1.5,
        windupMs: 700,
        impactMs: 800,
        recoveryMs: 600,
        rangePx: 240,
        arcDegrees: 40,
        damageMultiplier: 0.6,
        cooldownMs: 2600,
      },
      telegraphMs: 600,
      xpReward: 16,
      goldReward: 8,
      materialsReward: 2,
      animationIds: [
        'enemy.dark_shaman.idle.down',
        'enemy.dark_shaman.moving.down',
        'enemy.dark_shaman.use_ability.down',
      ],
      frameSize: 64,
    },
    {
      enemyId: 'root_brute',
      tuningStatus: 'PROVISIONAL',
      maxHealth: 90,
      armor: 12,
      moveSpeedPxPerSec: 65,
      separationRadiusPx: 34,
      detectRadiusPx: 200,
      loseTargetRadiusPx: 300,
      leashRadiusPx: 400,
      attack: {
        weaponDamage: [10, 14],
        power: 4,
        level: 1,
        criticalChance: 0.05,
        criticalMultiplier: 1.5,
        windupMs: 800,
        impactMs: 900,
        recoveryMs: 700,
        rangePx: 90,
        arcDegrees: 140,
        damageMultiplier: 1.4,
        cooldownMs: 2200,
      },
      telegraphMs: 700,
      xpReward: 24,
      goldReward: 12,
      materialsReward: 3,
      animationIds: [
        'enemy.root_brute.idle.down',
        'enemy.root_brute.moving.down',
        'enemy.root_brute.attacking.down',
      ],
      frameSize: 128,
    },
    {
      enemyId: 'unstable_beast',
      tuningStatus: 'PROVISIONAL',
      maxHealth: 50,
      armor: 4,
      moveSpeedPxPerSec: 140,
      separationRadiusPx: 26,
      detectRadiusPx: 240,
      loseTargetRadiusPx: 360,
      leashRadiusPx: 460,
      attack: {
        weaponDamage: [12, 16],
        power: 5,
        level: 1,
        criticalChance: 0.06,
        criticalMultiplier: 1.5,
        windupMs: 900,
        impactMs: 950,
        recoveryMs: 800,
        rangePx: 110,
        arcDegrees: 360,
        damageMultiplier: 1.8,
        cooldownMs: 3000,
      },
      telegraphMs: 900,
      xpReward: 20,
      goldReward: 10,
      materialsReward: 2,
      animationIds: [
        'enemy.unstable_beast.idle.down',
        'enemy.unstable_beast.moving.down',
        'enemy.unstable_beast.attacking.down',
      ],
      frameSize: 64,
    },
  ],
  enemyAbilityTuning: {
    tuningStatus: 'PROVISIONAL',
    // Chamán (dark_shaman): restores half of an ally's missing health, ignores near-full allies.
    healAllies: { healMissingFraction: 0.5, ignoreAboveFraction: 0.9 },
    // Bruto (root_brute): 90px burst around the caster, 1.2s stun on those hit.
    areaAttack: { radiusPx: 90, stunMs: 1200 },
    // Bestia (unstable_beast): 90px death burst announced 900ms ahead, 1.8x damage.
    explosion: { radiusPx: 90, telegraphMs: 900, damageMultiplier: 1.8 },
    // Arquero (possessed_archer): slow visible bolt, ~attack.range reach, 16px contact radius.
    ranged: { projectileSpeedPxPerSec: 400, projectileMaxRangePx: 260, hitRadiusPx: 16 },
  },
  endlessForest: {
    tuningStatus: 'PROVISIONAL',
    minimumLevel: 1,
    maximumLevel: 20,
    levels: buildEndlessForestLevels(),
  },
  zone: {
    id: 'corrupted_forest',
    displayName: 'Bosque Corrupto',
    awayModeEligible: true,
    enemyIds: [
      'corrupted_minion',
      'possessed_archer',
      'dark_shaman',
      'root_brute',
      'unstable_beast',
    ],
    mapId: 'map.corrupted_forest',
    tuningStatus: 'TBD',
  },
  mission: {
    id: 'mission.corrupted_forest.breach',
    zoneId: 'corrupted_forest',
    objectives: [
      { type: 'destroy_altars', count: 3 },
      { type: 'defeat_boss', enemyId: 'corrupted_guardian' },
    ],
    tuningStatus: 'TBD',
  },
  spriteSheets: [
    {
      id: 'spritesheet.guardian.body.placeholder',
      frameWidth: 64,
      frameHeight: 64,
      frameCount: 4,
      origin: { x: 0.5, y: 1 },
      offset: { x: 0, y: 0 },
      directions: ['up', 'down', 'left', 'right'],
      mirrorLeftFromRight: true,
    },
  ],
  animations: [
    {
      id: 'guardian.idle.down',
      atlasId: 'spritesheet.guardian.body.placeholder',
      state: 'idle',
      direction: 'down',
      startFrame: 0,
      endFrame: 3,
      frameRate: 1,
      repeat: -1,
      lockMovement: false,
      interruptible: true,
      eventFrames: [],
    },
    {
      id: 'guardian.attack_basic.down',
      atlasId: 'spritesheet.guardian.body.placeholder',
      state: 'attacking',
      direction: 'down',
      startFrame: 0,
      endFrame: 3,
      frameRate: 10,
      repeat: 0,
      lockMovement: true,
      interruptible: false,
      hitFrame: 2,
      eventFrames: [{ frame: 2, event: 'combat.hit_window' }],
    },
    {
      id: 'guardian.skill_power_strike.down',
      atlasId: 'spritesheet.guardian.body.placeholder',
      state: 'casting',
      direction: 'down',
      startFrame: 0,
      endFrame: 3,
      frameRate: 5,
      repeat: 0,
      lockMovement: true,
      interruptible: false,
      hitFrame: 2,
      eventFrames: [{ frame: 2, event: 'combat.hit_window' }],
    },
    {
      id: 'guardian.skill_whirlwind.down',
      atlasId: 'spritesheet.guardian.body.placeholder',
      state: 'channeling',
      direction: 'down',
      startFrame: 0,
      endFrame: 3,
      frameRate: 40 / 3,
      repeat: 0,
      lockMovement: false,
      interruptible: true,
      eventFrames: [],
    },
    {
      id: 'guardian.skill_iron_skin.down',
      atlasId: 'spritesheet.guardian.body.placeholder',
      state: 'casting',
      direction: 'down',
      startFrame: 0,
      endFrame: 3,
      frameRate: 8,
      repeat: 0,
      lockMovement: false,
      interruptible: true,
      eventFrames: [],
    },
  ],
  assets: [
    {
      id: 'spritesheet.guardian.body.placeholder',
      type: 'spritesheet',
      path: '/assets/characters/guardian_body_placeholder.png',
      version: GAME_DATA_VERSION,
      preload: true,
      source: 'Proyecto La Brecha Oscura',
      author: 'Pendiente de producción',
      license: 'Placeholder interno',
      addedOn: '2026-07-29',
      approximateBytes: 0,
      animationIds: [
        'guardian.idle.down',
        'guardian.attack_basic.down',
        'guardian.skill_power_strike.down',
        'guardian.skill_whirlwind.down',
        'guardian.skill_iron_skin.down',
      ],
      spriteSheet: {
        id: 'spritesheet.guardian.body.placeholder',
        frameWidth: 64,
        frameHeight: 64,
        frameCount: 4,
        origin: { x: 0.5, y: 1 },
        offset: { x: 0, y: 0 },
        directions: ['up', 'down', 'left', 'right'],
        mirrorLeftFromRight: true,
      },
    },
  ],
  maps: [
    {
      id: 'map.corrupted_forest',
      format: 'tiled',
      version: GAME_DATA_VERSION,
      requiredLayers: [
        'ground',
        'decoration_lower',
        'collisions',
        'interactive_objects',
        'obstacles',
        'decoration_upper',
        'spawn_zones',
        'camera_zones',
        'altars',
        'doors',
        'portal',
        'boss_arena',
        'checkpoints',
        'ambient_sound',
        'minimap',
      ],
      objects: [
        {
          entityType: 'altar',
          definitionId: 'objective.corrupted_altar',
          objectiveId: 'objective.destroy_altars',
          serverRelevant: true,
        },
        {
          entityType: 'door',
          definitionId: 'door.corrupted_forest.boss',
          interactionId: 'interaction.open_boss_door',
          serverRelevant: true,
        },
        {
          entityType: 'boss_arena',
          definitionId: 'arena.corrupted_guardian',
          serverRelevant: true,
        },
      ],
    },
  ],
  hazards: [
    {
      id: 'hazard.corrupted_pulse',
      displayName: 'Pulso corrupto',
      periodMs: 4000,
      telegraphMs: 900,
      radiusPx: 90,
      damage: 18,
      lethal: false,
    },
  ],
  // M1 of the post-MVP class expansion (docs/plans/post-goal-class-expansion.md): the registry
  // shape proven against Guardian. dark_knight/arcanist/hunter/summoner join with empty
  // branchIds/nodes until their vertical slice (M2) is designed and their art is budgeted — an
  // empty branch list is a valid, intentional starting state, not a placeholder to fill blindly.
  classRegistry: {
    registryVersion: 'class-registry.1',
    classes: [
      {
        classId: 'guardian',
        schemaVersion: 'class-registry.1',
        displayName: 'Guardián',
        roleTags: ['melee_resilient'],
        resource: 'fury',
        attributeIds: ['strength', 'dexterity', 'intelligence', 'vitality'],
        branchIds: [],
      },
    ],
    branches: [],
    nodes: [],
  },
};
